from importlib.metadata import version
from pathlib import Path

import toml

from hibachi_xyz.api import HibachiApiClient, price_to_bytes
from hibachi_xyz.api_ws_account import HibachiWSAccountClient
from hibachi_xyz.api_ws_market import HibachiWSMarketClient
from hibachi_xyz.api_ws_trade import HibachiWSTradeClient
from hibachi_xyz.errors import (
    BaseError,
    DeserializationError,
    ExchangeError,
    HttpConnectionError,
    MissingCredentialsError,
    SerializationError,
    TransportError,
    TransportTimeoutError,
    ValidationError,
    WebSocketConnectionError,
    WebSocketMessageError,
)
from hibachi_xyz.types import (
    AccountInfo,
    AccountSnapshot,
    AccountStreamStartResult,
    AccountTrade,
    AccountTradesResponse,
    Asset,
    BatchOrder,
    BatchResponse,
    BatchResponseOrder,
    CancelOrder,
    CapitalBalance,
    CapitalHistory,
    CreateOrder,
    CrossChainAsset,
    DepositInfo,
    EnableCancelOnDisconnectParams,
    ExchangeInfo,
    FeeConfig,
    FundingRateEstimation,
    FutureContract,
    HibachiApiError,
    Interval,
    InventoryResponse,
    Kline,
    KlinesResponse,
    MaintenanceWindow,
    Market,
    MarketInfo,
    Nonce,
    OpenInterestResponse,
    Order,
    OrderBook,
    OrderBookLevel,
    OrderCancelParams,
    OrderFlags,
    OrderId,
    OrderIdVariant,
    OrderModifyParams,
    OrderPlaceParams,
    OrderPlaceResponse,
    OrderPlaceResponseResult,
    OrderResponse,
    OrdersBatchParams,
    OrdersCancelParams,
    OrdersStatusParams,
    OrdersStatusResponse,
    OrderStatus,
    OrderStatusParams,
    OrderStatusResponse,
    OrderType,
    PendingOrdersResponse,
    Position,
    PriceResponse,
    Settlement,
    SettlementsResponse,
    Side,
    StatsResponse,
    TakerSide,
    TPSLConfig,
    Trade,
    TradesResponse,
    TradingTier,
    Transaction,
    TransferRequest,
    TransferResponse,
    TriggerDirection,
    TWAPConfig,
    TWAPQuantityMode,
    UpdateOrder,
    WebSocketBatchOrder,
    WebSocketEvent,
    WebSocketMarketSubscriptionListResponse,
    WebSocketOrderCancelParams,
    WebSocketOrderModifyParams,
    WebSocketOrdersBatchParams,
    WebSocketOrdersCancelParams,
    WebSocketOrdersStatusParams,
    WebSocketOrderStatusParams,
    WebSocketResponse,
    WebSocketStreamPingParams,
    WebSocketStreamStartParams,
    WebSocketStreamStopParams,
    WebSocketSubscription,
    WebSocketSubscriptionTopic,
    WithdrawalLimit,
    WithdrawRequest,
    WithdrawResponse,
)


def get_version() -> str:
    """Return the version of the hibachi library package."""
    pyproject_path = Path(__file__).parents[1] / "pyproject.toml"
    if pyproject_path.exists():
        with open(pyproject_path) as f:
            pyproject = toml.loads(f.read())

        return pyproject["project"]["version"]

    return version("hibachi_xyz")


__version__: str = get_version()
__all__ = [
    "HibachiApiClient",
    "HibachiApiError",
    "BaseError",
    "ExchangeError",
    "TransportError",
    "ValidationError",
    "MissingCredentialsError",
    "HttpConnectionError",
    "TransportTimeoutError",
    "WebSocketConnectionError",
    "WebSocketMessageError",
    "DeserializationError",
    "SerializationError",
    "Interval",
    "Nonce",
    "OrderId",
    "Side",
    "TWAPConfig",
    "TWAPQuantityMode",
    "CreateOrder",
    "UpdateOrder",
    "CancelOrder",
    "HibachiWSMarketClient",
    "HibachiWSTradeClient",
    "HibachiWSAccountClient",
    "price_to_bytes",
    "OrderIdVariant",
    "TPSLConfig",
    "OrderType",
    "TriggerDirection",
    "OrderStatus",
    "OrderFlags",
    "Order",
    "FeeConfig",
    "FutureContract",
    "WithdrawalLimit",
    "MaintenanceWindow",
    "ExchangeInfo",
    "FundingRateEstimation",
    "PriceResponse",
    "BatchResponseOrder",
    "BatchResponse",
    "StatsResponse",
    "TakerSide",
    "Trade",
    "TradesResponse",
    "Kline",
    "KlinesResponse",
    "OpenInterestResponse",
    "OrderBookLevel",
    "OrderBook",
    "Asset",
    "Position",
    "AccountInfo",
    "AccountTrade",
    "AccountTradesResponse",
    "Settlement",
    "SettlementsResponse",
    "PendingOrdersResponse",
    "CapitalBalance",
    "Transaction",
    "CapitalHistory",
    "WithdrawRequest",
    "WithdrawResponse",
    "TransferRequest",
    "TransferResponse",
    "DepositInfo",
    "WebSocketSubscriptionTopic",
    "WebSocketSubscription",
    "WebSocketMarketSubscriptionListResponse",
    "WebSocketResponse",
    "WebSocketEvent",
    "WebSocketOrderCancelParams",
    "WebSocketOrderModifyParams",
    "WebSocketOrderStatusParams",
    "WebSocketOrdersStatusParams",
    "WebSocketOrdersCancelParams",
    "WebSocketBatchOrder",
    "WebSocketOrdersBatchParams",
    "WebSocketStreamStartParams",
    "WebSocketStreamPingParams",
    "WebSocketStreamStopParams",
    "AccountSnapshot",
    "AccountStreamStartResult",
    "OrderPlaceParams",
    "OrderCancelParams",
    "OrderModifyParams",
    "OrderStatusParams",
    "OrdersStatusParams",
    "OrdersCancelParams",
    "BatchOrder",
    "OrdersBatchParams",
    "EnableCancelOnDisconnectParams",
    "OrderResponse",
    "OrderPlaceResponseResult",
    "OrderPlaceResponse",
    "OrdersStatusResponse",
    "OrderStatusResponse",
    "CrossChainAsset",
    "TradingTier",
    "MarketInfo",
    "Market",
    "InventoryResponse",
    "__version__",
]
