"""Base strategy classes and signal types."""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from decimal import Decimal
from enum import Enum, auto
from typing import Any

import pandas as pd


class SignalType(Enum):
    """Type of trading signal."""

    LONG = auto()
    SHORT = auto()
    CLOSE_LONG = auto()
    CLOSE_SHORT = auto()
    NONE = auto()


@dataclass
class Signal:
    """Trading signal generated by a strategy.

    Attributes:
        signal_type: Type of signal (LONG, SHORT, CLOSE, etc.)
        symbol: Trading pair symbol
        strength: Signal strength (0.0 to 1.0)
        price: Entry price recommendation
        stop_loss: Stop loss price
        take_profit: Take profit price
        metadata: Additional strategy-specific metadata
        timestamp: Signal generation timestamp
    """

    signal_type: SignalType
    symbol: str
    strength: float = 1.0
    price: Decimal | None = None
    stop_loss: Decimal | None = None
    take_profit: Decimal | None = None
    metadata: dict[str, Any] | None = None
    timestamp: int | None = None

    @property
    def is_entry(self) -> bool:
        """Check if signal is an entry signal."""
        return self.signal_type in (SignalType.LONG, SignalType.SHORT)

    @property
    def is_exit(self) -> bool:
        """Check if signal is an exit signal."""
        return self.signal_type in (SignalType.CLOSE_LONG, SignalType.CLOSE_SHORT)


class Strategy(ABC):
    """Abstract base class for trading strategies.

    All strategies must implement the generate_signal method.
    """

    def __init__(self, name: str) -> None:
        """Initialize the strategy.

        Args:
            name: Strategy name for identification
        """
        self.name = name

    @abstractmethod
    def generate_signal(
        self,
        symbol: str,
        df: pd.DataFrame,
        current_price: Decimal,
        position: dict[str, Any] | None = None,
    ) -> Signal:
        """Generate a trading signal based on market data.

        Args:
            symbol: Trading pair symbol
            df: DataFrame with OHLCV and indicator data
            current_price: Current market price
            position: Current position info (if any)

        Returns:
            Signal object with trading recommendation
        """
        pass

    def validate_data(self, df: pd.DataFrame, required_columns: list[str]) -> bool:
        """Validate that DataFrame has required columns.

        Args:
            df: DataFrame to validate
            required_columns: List of required column names

        Returns:
            True if all required columns are present
        """
        return all(col in df.columns for col in required_columns)
